apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "false"
    usePodIdentity: "false"
    userAssignedIdentityID: ""
    subscriptionId: "b214611b-9a79-4e7e-afb0-3d9785737f10"
    tenantId: "0e97f85a-b424-40f3-8fcc-bdde6023332e"
    resourceGroup: "Intel_RG_01"
    keyvaultName: "AKSKeyVault90501861263"
    objects: |
      array:
        - |
            objectName: TestKey
            objectType: secret      # object types: secret, key or cert
    cloudName: AzurePublicCloud