apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "false"
    usePodIdentity: "false"
    userAssignedIdentityID: "63c7ebc3-43c9-4243-ac7a-a58003125557"
    subscriptionId: b214611b-9a79-4e7e-afb0-3d9785737f10
    tenantId: 0e97f85a-b424-40f3-8fcc-bdde6023332e
    resourceGroup: BCG-RG
    keyvaultName: AKSKeyVault39173152362
    objects: |
      array:
        - |
            objectName: TestKey
            objectType: secret      # object types: secret, key or cert
    cloudName: AzurePublicCloud